# Generated by Django 3.2.7 on 2021-10-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflearn_lecture', '0006_auto_20211004_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytext',
            name='lecture_video1',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='mytext',
            name='lecture_video2',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='mytext',
            name='lecture_video3',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='mytext',
            name='lecture_video4',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
